server:
  port: 8081
# application.yml
spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/auth_db
    username: app_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Use 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@eureka-discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    non-secure-port: 8081


logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.security: DEBUG
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.hibernate.SQL: DEBUG                       # Shows SQL queries if using JPA
    org.springframework.boot.autoconfigure: DEBUG