apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-discovery-service
  template:
    metadata:
      labels:
        app: eureka-discovery-service
    spec:
      containers:
        - name: eureka
          image: kdurgesh029/eureka-discovery-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-discovery-service
spec:
  selector:
    app: eureka-discovery-service
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30061        # Exposes Eureka on your host node at port 30061
  type: NodePort
