server:
  port: 8761

spring:
  application:
    name: discovery-server
  security:
      user:
        name: admin
        password: admin123

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@eureka-discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true



