server:
  port: 8082

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@eureka-discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
