server:
  port: 80

spring:
  application:
    name: api-gateway-service
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
