server:
  port: 80

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/products/**
  webflux:
    multipart:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@eureka-discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE