server:
  port: 80

spring:
  web:
    log-request-details: true
  application:
    name: api-gateway-service
  cloud:
    gateway:
#      default-filters:
#        - name: PreserveHostHeader
#        - name: RequestSize
#          args:
#            maxSize: 10MB
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth-service
                timeoutDuration: 3000  # 3 seconds instead of 1
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user-service
                timeoutDuration: 3000  # 3 seconds instead of 1

        - id: product
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/fallback/product-service
                timeoutDuration: 3000  # 3 seconds instead of 1
  webflux:
    multipart:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@eureka-discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
#    root: DEBUG
#    org.springframework: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.cloud: DEBUG
#    reactor.netty: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG